### ISSUE TITLE
Доработка функционала - формат UltraStar

### ISSUE THREAD

**Issue by lexx1971** [MadLord80/KFN_Viewer#1]
Добрый день.
Алексей, возникла необходимость добавить ещё один алгоритм конвертирования лирики для EMZ-файлов.
Дело в том, что в последних версиях проигрывателя Encore Игорь добавил возможность проигрывания нового формата караоке - ULTRASTAR.
http://support.encore.su/viewtopic.php?pid=368#p368
Одновременно с этим, даже чуть ранее он запретил в плеере проигрывание нешифрованых EMZ-файлов. Т.е. теперь штатный EMZ-файл проигрывается только в том случае, если он записан с помощью редактора Encore и зашифрован ключом логина плеера. Получается, что фонограмма EMZ теперь должна быть привязана к каждой копии плеера индивидуально, что создаёт проблемы для распространения фонограмм, выпущенных не Игорем, а сторонними писателями, иначе при проигрывании незашифрованой фонограммы текст лирики не отображается, но при этом воспроизводится звук и видео.
В ходе экспериментов я обнаружил, что если воспользоваться редактором караоке ULTRASTAR и создать в нём лирику, которая в этом редакторе штатно сохраняется в файл TXT, а потом добавить её в файл EMZ вместо энкоровского файла лирики ELYR, то при воспроизведении такого EMZ в новой версии плеера всё работает как нужно. Воспроизводится и звук и видео и лирика. При этом лирика получается внутри EMZ не шифрованная.
Собственно, в связи с этим хотел попросить сделать возможность в конвертере KFN_Viewer добавить возможность:
1. конвертировать лирику расширенного формата LRC в лирику формата ULTRASTAR и обратно,
2. конвертировать лирику формата ELYR в лирику формата ULTRASTAR и обратно,
3. пересобирать нешифрованый файл EMZ из стандартного формата в формат AVI+MP3+TXT(ULTRASTAR).
Можно такое будет такое реализовать в дальнейших версиях KFN_Viewer?

**Comment by lexx1971** [comment]
Вот здесь UltraStar Creator - https://sourceforge.net/projects/usc/
Можно ещё добавить функцию перевода из формата ULTRASTAR в EMZ. Для этого нужно просто 3-м файлам MP3, MP4 и TXT (или двум без MP4), которые в сумме представляют собой фонограмму караоке в ULTRASTAR дать одинаковые имена (за исключением расширения), запаковать в ZIP-архив и у полученного архивного ZIP-файла изменить расширение на EMZ. Имя файлу EMZ нужно присваивать в формате - <Имя исполнителя>=<Название песни>.emz

**Comment by MadLord80** [comment]
Да, посмотрю, что можно сделать...

**Comment by MadLord80** [comment]
посмотрел на формат UltraStar...есть там один момент: данный формат в качестве временных меток использует метки ударов, которые рассчитываются на основе BPM (количество ударов в минуту или темп) песни...т.е. чтобы количество ударов перевести во временную метку, нужно знать BPM песни...
данный BPM в большинстве случаев не указывается в тэгах ID3 и его нужно получать анализируя сам файл песни...реализации есть, их можно использовать, но вот насколько они точно определяют BPM - это вопрос...

**Comment by MadLord80** [comment]
Перенесено в новый проект - [#5](https://github.com/MadLord80/karamad/issues/5)
