### ISSUE TITLE
modify song.ini

### ISSUE THREAD

**Issue by frebor123** [MadLord80/KFN_Viewer#2]
Hello.
Is there a way to  edit song.ini or import song.ini and create another kfn  ?
Thx for your great job !

**Comment by MadLord80** [comment]
Not yet, but can be done.

**Comment by MadLord80** [comment]
You can extract all files from *.kfn and create new kfn with Karafan Studio.

**Comment by MadLord80** [comment]
Перенесено в новый проект - [#4](https://github.com/MadLord80/karamad/issues/4)
