### ISSUE TITLE
Encore-формат KFN

### ISSUE THREAD

**Issue by ghost** [MadLord80/KFN_Viewer#3]
У меня есть база на 200Гб KFN файлов с испорченными заголовками:
![image](https://user-images.githubusercontent.com/77649409/104975358-86f0cc00-5a0b-11eb-8976-233d2856906e.png)

Вот так выглядят нормальные заголовки:
![image](https://user-images.githubusercontent.com/77649409/104975409-9ec85000-5a0b-11eb-97a0-87bf0ab6d0a2.png)

Скриншоты сделал в [hexed.it](https://hexed.it/).

Я не очень хорошо разбираюсь в структуре формата KFN, но вставив заголовок из хорошего файла в испорченный у меня получилось заставить KFN_Viewer экспортировать песенку из файла, но с неправильной длинной.

Музыка в этих файлах обычная - в незашифрованном mp3 (можно скормить в VLC и он будет её играть), а формат текста вроде ничем не отличается от обычного KFN - когда я в HEX сравнивал их side-by-side.

Этот "испорченный" формат умеет играть Encore Pro - это специально испорченный формат созданный Encore чтобы игрался только в их плеере.

Идея в том, чтобы научить прогу читать такие файлы и конвертировать в нормальные. Я и сам могу этим заняться и скинуть PR, но мне нужна помощь в том, чтобы разобраться в структуре заголовков.

База большая и почти уникальная, так что добавить поддержку такого формата будет полезно, как мне кажется. Архив с несколькими песнями с испорченными заголовками:
[bad.zip](https://github.com/MadLord80/KFN_Viewer/files/5832986/bad.zip)

Сравнивал заголовки я с этими песнями, которые были под рукой:
[good.zip](https://github.com/MadLord80/KFN_Viewer/files/5832990/good.zip)

При изучении этого странного "недоKFN" формата я опирался на:
http://www.ulduzsoft.com/2012/10/reverse-engineering-the-karafun-file-format-part-1-the-header/
http://www.ulduzsoft.com/2012/10/reverse-engineering-the-karafun-file-format-part-2-the-directory/
https://gitlab.com/morsik/karafun-spec/blob/master/Readme.md

**Comment by MadLord80** [comment]
Да, я знаком с таким форматом KFN. Мне казалось, что он должен быть шифрован под конкретный купленный Encore - разве не так? Эти файлы на другом плеере Ecnore работают?

**Comment by ghost** [comment]
@MadLord80 посмотри пример файлов в HEX - они вообще не шифрованные. они работают на любом оплаченном Encore Pro. похожи на обычный KFN с испорченными заголовками. это из публичной базы которая подходит для любого оплаченного Encore

**Comment by MadLord80** [comment]
> разобраться в структуре заголовков

Ну в этом то и вся проблема по сути...готовы ли Вы выложить для решения этой проблемы сумму в 5000р?...)))

**Comment by ghost** [comment]
@MadLord80 чего ?)

**Comment by MadLord80** [comment]
Эта база данных KFN куплена авторами Encore за 5000р у сайта karafun-karaoke.ru. После чего они (авторы Encore) у себя заменили все заголовки файлов своим волшебным методом. Отсюда вопрос: что проще - сидеть и разгадывать "их метод" или просто купить ту жу базу за 5000р уже с нормальными заголовками?...

**Comment by ghost** [comment]
@MadLord80 а как же спортивный интерес разобрать непонятный формат ?) ну и там всякие моральные принципы - не кормить воров кто друг у друга перепродаёт базу которая никому из них не принадлежит - остановить караоке мафию, все дела

**Comment by Harchvertelol** [comment]
Добрый день!

Дело в том, что у них там не только база за 5000, там есть ещё одна база (она с сайта encore-russia). Получается, есть возможность получить сразу две базы, разобравшись в заголовках и шифровании (если есть, но, как сказал человек выше, шифрования нет). А личка есть на гитхабе, чтобы связаться напрямую? Или любые другие способы связи, чтобы не обсуждать здесь?

**Comment by MadLord80** [comment]
?

  
>Вторник, 11 июля 2023, 22:45 +07:00 от Harch ***@***.***>:
> 
> 
>Добрый день!
>Дело в том, что у них там не только база за 5000, там есть ещё одна база (она с сайта encore-russia). Получается, есть возможность получить сразу две базы, разобравшись в заголовках и шифровании (если есть, но, как сказал человек выше, шифрования нет). А личка есть на гитхабе, чтобы связаться напрямую? Или любые другие способы связи, чтобы не обсуждать здесь?
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you were mentioned. Message ID:  <MadLord80/KFN_Viewer/issues/3/1631067052 @ github . com> 
 
 
С уважением, Павлов Алексей :-)

**Comment by MadLord80** [comment]
Перенесено в новый проект - [#3](https://github.com/MadLord80/karamad/issues/3)
