### ISSUE TITLE
Формат .yrd

### ISSUE THREAD

**Issue by DonArkidon** [MadLord80/KFN_Viewer#4]
Доброго времени суток! Есть такой караоке плеер YourDay, у них песни в формате .yrd. Как конвертировать .kfn в формат .yrd? Спасибо за внимание!

**Comment by MadLord80** [comment]
Ну приблизительно понятно. Yrd - обычный архив с файлами. В отдельном файле (lyrics.lyric) лежит лирика - кодировка текста используется 1251. Формат файла, конечно, проприетарный, но вроде разобраться можно. Хорошо, посмотрю.

**Comment by MadLord80** [comment]
Перенесено в новый проект - [#2](https://github.com/MadLord80/karamad/issues/2)
