### ISSUE TITLE
LRC enhanced format issue

### ISSUE THREAD

**Issue by mixage** [MadLord80/KFN_Viewer#5]
https://en.wikipedia.org/wiki/LRC_(file_format)#Simple_format_extended

As my understanding, the LRC enhanced format states that every hyphens must be preceded by a time stamp in the **\<mm:ss.xx\>** format, so:

[mm:ss.xx]\<mm:ss.xx\>**line 1 word 1** \<mm:ss.xx\>**line 1 word 2** ... should be OK
[mm:ss.xx]**line 1 word 1** \<mm:ss.xx\>**line 1 word 2** ... seems to be BAD

Can you fix this? Thanks for your great work :)

**Comment by MadLord80** [comment]
Перенесено в новый проект - [#1](https://github.com/MadLord80/karamad/issues/1)
